[workspace]
members = [
    "fmu_from_struct",
    "fmu_from_struct_derive"
, "package_fmu_after_build"]
exclude = [
    "examples",
    "fmu_build_utils"
]

resolver = "2"

[patch.crates-io]
fmu_from_struct = { path = "fmu_from_struct" }

[workspace.dependencies]
libc = "0.2.151"
