[package]
name = "spring"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fmu_from_struct = { path = "../../fmu_from_struct" }

[features]
default = ["fmi2"]  # Default to FMI version 2
fmi2 = []
fmi3 = []
